
using SDMChartApp.Models; 

namespace SDMChartApp.Services // Replace with your actual namespace
{
    public class SDMService
    {        
        public async Task<Dictionary<string, List<string>>> GetSDMPieChartDataAsync()
        {
            return new Dictionary<string, List<string>>
            {
                { "SDM", new List<string> { "0-7 GB", "7-8 GB", ">=8 GB", "Missing Data" } },
                { "SDM_IF_TR", new List<string> { "0-7 MB", "7-10 MB", ">=10 MB", "Missing Data" } },
                { "SDM_IF_POS", new List<string> { "0-7 MB", "7-10 MB", ">=10 MB", "Missing Data" } },
                { "SDM_Log_File", new List<string> { "0.0-0.5 GB", "0.5-1 GB", ">=1 GB", "Missing Data" } }
            };
        }

        public async Task<List<SDMTableRow>> GetSDMTableDataAsync()
        {
            return new List<SDMTableRow>
            {
                new SDMTableRow { DatabaseType="SDM", Segment = "IOM LEAD", Market = "UK", StoreId = "000001", StoreName = "Store001", DBSizeGB = 7500,  DBUsedPercent = 10,  DBAvailableGB = 2,   DBAvailablePercent = 25, LastBackupOn = DateTime.Parse("2025-01-01") },
                new SDMTableRow { DatabaseType="SDM", Segment = "IOM LEAD", Market = "US", StoreId = "000002", StoreName = "Store002", DBSizeGB = 6200,  DBUsedPercent = 20,  DBAvailableGB = 3,   DBAvailablePercent = 35, LastBackupOn = DateTime.Parse("2025-02-01") },
                new SDMTableRow { DatabaseType="SDM", Segment = "IOM LEAD", Market = "CA", StoreId = "000003", StoreName = "Store003", DBSizeGB = 5800,  DBUsedPercent = 30,  DBAvailableGB = 4,   DBAvailablePercent = 45, LastBackupOn = DateTime.Parse("2025-03-01") },
                new SDMTableRow { DatabaseType="SDM", Segment = "IOM LEAD", Market = "IN", StoreId = "000004", StoreName = "Store004", DBSizeGB = 3578,  DBUsedPercent = 40,  DBAvailableGB = 2.5, DBAvailablePercent = 30, LastBackupOn = DateTime.Parse("2025-04-01") },
                new SDMTableRow { DatabaseType="SDM", Segment = "IOM LEAD", Market = "UK", StoreId = "000005", StoreName = "Store005", DBSizeGB = 9000,  DBUsedPercent = 50,  DBAvailableGB = 1.5, DBAvailablePercent = 20, LastBackupOn = DateTime.Parse("2025-05-01") },
                new SDMTableRow { DatabaseType="SDM", Segment = "IOM LEAD", Market = "US", StoreId = "000006", StoreName = "Store006", DBSizeGB = 0.0,  DBUsedPercent = 60,  DBAvailableGB = 3.3, DBAvailablePercent = 41, LastBackupOn = DateTime.Parse("2025-06-01") },
                new SDMTableRow { DatabaseType="SDM", Segment = "IOM LEAD", Market = "CA", StoreId = "000007", StoreName = "Store007", DBSizeGB = 6500,  DBUsedPercent = 70,  DBAvailableGB = 2.1, DBAvailablePercent = 25, LastBackupOn = DateTime.Parse("2025-07-01") },
                new SDMTableRow { DatabaseType="SDM", Segment = "IOM LEAD", Market = "IN", StoreId = "000008", StoreName = "Store008", DBSizeGB = 10000, DBUsedPercent = 80,  DBAvailableGB = 1.2, DBAvailablePercent = 15, LastBackupOn = DateTime.Parse("2025-08-01") },
                new SDMTableRow { DatabaseType="SDM", Segment = "IOM LEAD", Market = "UK", StoreId = "000009", StoreName = "Store009", DBSizeGB = 3500,  DBUsedPercent = 90,  DBAvailableGB = 0.5, DBAvailablePercent = 10, LastBackupOn = DateTime.Parse("2025-09-01") },
                new SDMTableRow { DatabaseType="SDM", Segment = "IOM LEAD", Market = "US", StoreId = "000010", StoreName = "Store010", DBSizeGB = 7000,  DBUsedPercent = 35,  DBAvailableGB = 3.0, DBAvailablePercent = 30, LastBackupOn = DateTime.Parse("2025-10-01") },
                new SDMTableRow { DatabaseType="SDM", Segment = "IOM LEAD", Market = "CA", StoreId = "000011", StoreName = "Store011", DBSizeGB = 6900,  DBUsedPercent = 55,  DBAvailableGB = 1.1, DBAvailablePercent = 15, LastBackupOn = DateTime.Parse("2025-11-01") },
                new SDMTableRow { DatabaseType="SDM", Segment = "IOM LEAD", Market = "IN", StoreId = "000012", StoreName = "Store012", DBSizeGB = 5500,  DBUsedPercent = 25,  DBAvailableGB = 2.5, DBAvailablePercent = 40, LastBackupOn = DateTime.Parse("2025-12-01") },
                new SDMTableRow { DatabaseType="SDM", Segment = "IOM LEAD", Market = "UK", StoreId = "000013", StoreName = "Store013", DBSizeGB = 1234,  DBUsedPercent = 15,  DBAvailableGB = 2.8, DBAvailablePercent = 32, LastBackupOn = DateTime.Parse("2025-01-15") },
                new SDMTableRow { DatabaseType="SDM", Segment = "IOM LEAD", Market = "US", StoreId = "000014", StoreName = "Store014", DBSizeGB = 5643,  DBUsedPercent = 45,  DBAvailableGB = 3.2, DBAvailablePercent = 38, LastBackupOn = DateTime.Parse("2025-02-15") },
                new SDMTableRow { DatabaseType="SDM", Segment = "IOM LEAD", Market = "CA", StoreId = "000015", StoreName = "Store015", DBSizeGB = 7200,  DBUsedPercent = 65,  DBAvailableGB = 1.0, DBAvailablePercent = 12, LastBackupOn = DateTime.Parse("2025-03-15") },
                new SDMTableRow { DatabaseType="SDM", Segment = "IOM LEAD", Market = "IN", StoreId = "000016", StoreName = "Store016", DBSizeGB = 4200,  DBUsedPercent = 85,  DBAvailableGB = 2.9, DBAvailablePercent = 22, LastBackupOn = DateTime.Parse("2025-04-15") },
                new SDMTableRow { DatabaseType="SDM", Segment = "IOM LEAD", Market = "UK", StoreId = "000017", StoreName = "Store017", DBSizeGB = 8600,  DBUsedPercent = 95,  DBAvailableGB = 0.7, DBAvailablePercent = 8,  LastBackupOn = DateTime.Parse("2025-05-15") },
                new SDMTableRow { DatabaseType="SDM", Segment = "IOM LEAD", Market = "US", StoreId = "000018", StoreName = "Store018", DBSizeGB = 6600,  DBUsedPercent = 5,   DBAvailableGB = 6.0, DBAvailablePercent = 90, LastBackupOn = DateTime.Parse("2025-06-15") },
                new SDMTableRow { DatabaseType="SDM", Segment = "IOM LEAD", Market = "CA", StoreId = "000019", StoreName = "Store019", DBSizeGB = 9300,  DBUsedPercent = 22,  DBAvailableGB = 7.1, DBAvailablePercent = 76, LastBackupOn = DateTime.Parse("2025-07-15") },
                new SDMTableRow { DatabaseType="SDM", Segment = "IOM LEAD", Market = "CA", StoreId = "000019", StoreName = "Store019", DBSizeGB = 0.0,  DBUsedPercent = 22,  DBAvailableGB = 7.1, DBAvailablePercent = 76, LastBackupOn = DateTime.Parse("2025-07-15") },

                new SDMTableRow { DatabaseType="SDM_IF_TR", Segment = "IOM LEAD", Market = "IN", StoreId = "000020", StoreName = "Store020", DBSizeGB = 1, DBUsedPercent = 100, DBAvailableGB = 0.0, DBAvailablePercent = 0, LastBackupOn = DateTime.Parse("2025-08-15") },
                new SDMTableRow { DatabaseType="SDM_IF_TR", Segment = "IOM LEAD", Market = "UK", StoreId = "000001", StoreName = "Store001", DBSizeGB = 5.3, DBUsedPercent = 10, DBAvailableGB = 2, DBAvailablePercent = 25, LastBackupOn = DateTime.Parse("2025-01-01") },
                new SDMTableRow { DatabaseType="SDM_IF_TR", Segment = "IOM LEAD", Market = "US", StoreId = "000002", StoreName = "Store002", DBSizeGB = 10, DBUsedPercent = 20, DBAvailableGB = 3, DBAvailablePercent = 35, LastBackupOn = DateTime.Parse("2025-02-01") },
                new SDMTableRow { DatabaseType="SDM_IF_TR", Segment = "IOM LEAD", Market = "CA", StoreId = "000003", StoreName = "Store003", DBSizeGB = 11, DBUsedPercent = 30, DBAvailableGB = 4, DBAvailablePercent = 45, LastBackupOn = DateTime.Parse("2025-03-01") },
                new SDMTableRow { DatabaseType="SDM_IF_TR", Segment = "IOM LEAD", Market = "IN", StoreId = "000004", StoreName = "Store004", DBSizeGB = 5, DBUsedPercent = 40, DBAvailableGB = 2.5, DBAvailablePercent = 30, LastBackupOn = DateTime.Parse("2025-04-01") },
                new SDMTableRow { DatabaseType="SDM_IF_TR", Segment = "IOM LEAD", Market = "UK", StoreId = "000005", StoreName = "Store005", DBSizeGB = 4.5, DBUsedPercent = 50, DBAvailableGB = 1.5, DBAvailablePercent = 20, LastBackupOn = DateTime.Parse("2025-05-01") },
                new SDMTableRow { DatabaseType="SDM_IF_TR", Segment = "IOM LEAD", Market = "US", StoreId = "000006", StoreName = "Store006", DBSizeGB = 14, DBUsedPercent = 60, DBAvailableGB = 3.3, DBAvailablePercent = 41, LastBackupOn = DateTime.Parse("2025-06-01") },
                new SDMTableRow { DatabaseType="SDM_IF_TR", Segment = "IOM LEAD", Market = "CA", StoreId = "000007", StoreName = "Store007", DBSizeGB = 2.2, DBUsedPercent = 70, DBAvailableGB = 2.1, DBAvailablePercent = 25, LastBackupOn = DateTime.Parse("2025-07-01") },
                new SDMTableRow { DatabaseType="SDM_IF_TR", Segment = "IOM LEAD", Market = "IN", StoreId = "000008", StoreName = "Store008", DBSizeGB = 7.4, DBUsedPercent = 80, DBAvailableGB = 1.2, DBAvailablePercent = 15, LastBackupOn = DateTime.Parse("2025-08-01") },
                new SDMTableRow { DatabaseType="SDM_IF_TR", Segment = "IOM LEAD", Market = "UK", StoreId = "000009", StoreName = "Store009", DBSizeGB = 6.3, DBUsedPercent = 90, DBAvailableGB = 0.5, DBAvailablePercent = 10, LastBackupOn = DateTime.Parse("2025-09-01") },
                new SDMTableRow { DatabaseType="SDM_IF_TR", Segment = "IOM LEAD", Market = "US", StoreId = "000010", StoreName = "Store010", DBSizeGB = 9.3, DBUsedPercent = 35, DBAvailableGB = 3.0, DBAvailablePercent = 30, LastBackupOn = DateTime.Parse("2025-10-01") },
                new SDMTableRow { DatabaseType="SDM_IF_TR", Segment = "IOM LEAD", Market = "CA", StoreId = "000011", StoreName = "Store011", DBSizeGB =8.8, DBUsedPercent = 55, DBAvailableGB = 1.1, DBAvailablePercent = 15, LastBackupOn = DateTime.Parse("2025-11-01") },
                new SDMTableRow { DatabaseType="SDM_IF_TR", Segment = "IOM LEAD", Market = "IN", StoreId = "000012", StoreName = "Store012", DBSizeGB = 3.8, DBUsedPercent = 25, DBAvailableGB = 2.5, DBAvailablePercent = 40, LastBackupOn = DateTime.Parse("2025-12-01") },
                new SDMTableRow { DatabaseType="SDM_IF_TR", Segment = "IOM LEAD", Market = "UK", StoreId = "000013", StoreName = "Store013", DBSizeGB = 10.4, DBUsedPercent = 15, DBAvailableGB = 2.8, DBAvailablePercent = 32, LastBackupOn = DateTime.Parse("2025-01-15") },
                new SDMTableRow { DatabaseType="SDM_IF_TR", Segment = "IOM LEAD", Market = "US", StoreId = "000014", StoreName = "Store014", DBSizeGB = 3.1, DBUsedPercent = 45, DBAvailableGB = 3.2, DBAvailablePercent = 38, LastBackupOn = DateTime.Parse("2025-02-15") },
                new SDMTableRow { DatabaseType="SDM_IF_TR", Segment = "IOM LEAD", Market = "CA", StoreId = "000015", StoreName = "Store015", DBSizeGB = 0.0, DBUsedPercent = 65, DBAvailableGB = 1.0, DBAvailablePercent = 12, LastBackupOn = DateTime.Parse("2025-03-15") },
                new SDMTableRow { DatabaseType="SDM_IF_TR", Segment = "IOM LEAD", Market = "IN", StoreId = "000016", StoreName = "Store016", DBSizeGB = 2.6, DBUsedPercent = 85, DBAvailableGB = 2.9, DBAvailablePercent = 22, LastBackupOn = DateTime.Parse("2025-04-15") },
                new SDMTableRow { DatabaseType="SDM_IF_TR", Segment = "IOM LEAD", Market = "UK", StoreId = "000017", StoreName = "Store017", DBSizeGB = 7.9, DBUsedPercent = 95, DBAvailableGB = 0.7, DBAvailablePercent = 8, LastBackupOn = DateTime.Parse("2025-05-15") },
                new SDMTableRow { DatabaseType="SDM_IF_TR", Segment = "IOM LEAD", Market = "US", StoreId = "000018", StoreName = "Store018", DBSizeGB = 1.7, DBUsedPercent = 5, DBAvailableGB = 6.0, DBAvailablePercent = 90, LastBackupOn = DateTime.Parse("2025-06-15") },
                new SDMTableRow { DatabaseType="SDM_IF_TR", Segment = "IOM LEAD", Market = "CA", StoreId = "000019", StoreName = "Store019", DBSizeGB = 0.0, DBUsedPercent = 22, DBAvailableGB = 7.1, DBAvailablePercent = 76, LastBackupOn = DateTime.Parse("2025-07-15") },

                new SDMTableRow { DatabaseType="SDM_IF_POS", Segment = "IOM LEAD", Market = "IN", StoreId = "000020", StoreName = "Store020", DBSizeGB = 1, DBUsedPercent = 100, DBAvailableGB = 0.0, DBAvailablePercent = 0, LastBackupOn = DateTime.Parse("2025-08-15") },
                new SDMTableRow { DatabaseType="SDM_IF_POS", Segment = "IOM LEAD", Market = "UK", StoreId = "000001", StoreName = "Store001", DBSizeGB = 5.3, DBUsedPercent = 10, DBAvailableGB = 2, DBAvailablePercent = 25, LastBackupOn = DateTime.Parse("2025-01-01") },
                new SDMTableRow { DatabaseType="SDM_IF_POS", Segment = "IOM LEAD", Market = "US", StoreId = "000002", StoreName = "Store002", DBSizeGB = 10, DBUsedPercent = 20, DBAvailableGB = 3, DBAvailablePercent = 35, LastBackupOn = DateTime.Parse("2025-02-01") },
                new SDMTableRow { DatabaseType="SDM_IF_POS", Segment = "IOM LEAD", Market = "CA", StoreId = "000003", StoreName = "Store003", DBSizeGB = 11, DBUsedPercent = 30, DBAvailableGB = 4, DBAvailablePercent = 45, LastBackupOn = DateTime.Parse("2025-03-01") },
                new SDMTableRow { DatabaseType="SDM_IF_POS", Segment = "IOM LEAD", Market = "IN", StoreId = "000004", StoreName = "Store004", DBSizeGB = 5, DBUsedPercent = 40, DBAvailableGB = 2.5, DBAvailablePercent = 30, LastBackupOn = DateTime.Parse("2025-04-01") },
                new SDMTableRow { DatabaseType="SDM_IF_POS", Segment = "IOM LEAD", Market = "UK", StoreId = "000005", StoreName = "Store005", DBSizeGB = 4.6, DBUsedPercent = 50, DBAvailableGB = 1.5, DBAvailablePercent = 20, LastBackupOn = DateTime.Parse("2025-05-01") },
                new SDMTableRow { DatabaseType="SDM_IF_POS", Segment = "IOM LEAD", Market = "US", StoreId = "000006", StoreName = "Store006", DBSizeGB = 8.3, DBUsedPercent = 60, DBAvailableGB = 3.3, DBAvailablePercent = 41, LastBackupOn = DateTime.Parse("2025-06-01") },
                new SDMTableRow { DatabaseType="SDM_IF_POS", Segment = "IOM LEAD", Market = "CA", StoreId = "000007", StoreName = "Store007", DBSizeGB = 9.9, DBUsedPercent = 70, DBAvailableGB = 2.1, DBAvailablePercent = 25, LastBackupOn = DateTime.Parse("2025-07-01") },
                new SDMTableRow { DatabaseType="SDM_IF_POS", Segment = "IOM LEAD", Market = "IN", StoreId = "000008", StoreName = "Store008", DBSizeGB = 10.9, DBUsedPercent = 80, DBAvailableGB = 1.2, DBAvailablePercent = 15, LastBackupOn = DateTime.Parse("2025-08-01") },
                new SDMTableRow { DatabaseType="SDM_IF_POS", Segment = "IOM LEAD", Market = "UK", StoreId = "000009", StoreName = "Store009", DBSizeGB = 6.4, DBUsedPercent = 90, DBAvailableGB = 0.5, DBAvailablePercent = 10, LastBackupOn = DateTime.Parse("2025-09-01") },
                new SDMTableRow { DatabaseType="SDM_IF_POS", Segment = "IOM LEAD", Market = "US", StoreId = "000010", StoreName = "Store010", DBSizeGB = 8.9, DBUsedPercent = 35, DBAvailableGB = 3.0, DBAvailablePercent = 30, LastBackupOn = DateTime.Parse("2025-10-01") },
                new SDMTableRow { DatabaseType="SDM_IF_POS", Segment = "IOM LEAD", Market = "CA", StoreId = "000011", StoreName = "Store011", DBSizeGB = 1.754, DBUsedPercent = 55, DBAvailableGB = 1.1, DBAvailablePercent = 15, LastBackupOn = DateTime.Parse("2025-11-01") },
                new SDMTableRow { DatabaseType="SDM_IF_POS", Segment = "IOM LEAD", Market = "IN", StoreId = "000012", StoreName = "Store012", DBSizeGB = 2.345, DBUsedPercent = 25, DBAvailableGB = 2.5, DBAvailablePercent = 40, LastBackupOn = DateTime.Parse("2025-12-01") },
                new SDMTableRow { DatabaseType="SDM_IF_POS", Segment = "IOM LEAD", Market = "UK", StoreId = "000013", StoreName = "Store013", DBSizeGB = 8.435, DBUsedPercent = 15, DBAvailableGB = 2.8, DBAvailablePercent = 32, LastBackupOn = DateTime.Parse("2025-01-15") },
                new SDMTableRow { DatabaseType="SDM_IF_POS", Segment = "IOM LEAD", Market = "US", StoreId = "000014", StoreName = "Store014", DBSizeGB = 0.0, DBUsedPercent = 45, DBAvailableGB = 3.2, DBAvailablePercent = 38, LastBackupOn = DateTime.Parse("2025-02-15") },
                new SDMTableRow { DatabaseType="SDM_IF_POS", Segment = "IOM LEAD", Market = "CA", StoreId = "000015", StoreName = "Store015", DBSizeGB = 0.5473, DBUsedPercent = 65, DBAvailableGB = 1.0, DBAvailablePercent = 12, LastBackupOn = DateTime.Parse("2025-03-15") },
                new SDMTableRow { DatabaseType="SDM_IF_POS", Segment = "IOM LEAD", Market = "IN", StoreId = "000016", StoreName = "Store016", DBSizeGB = 1.76, DBUsedPercent = 85, DBAvailableGB = 2.9, DBAvailablePercent = 22, LastBackupOn = DateTime.Parse("2025-04-15") },
                new SDMTableRow { DatabaseType="SDM_IF_POS", Segment = "IOM LEAD", Market = "UK", StoreId = "000017", StoreName = "Store017", DBSizeGB = 24.4543, DBUsedPercent = 95, DBAvailableGB = 0.7, DBAvailablePercent = 8, LastBackupOn = DateTime.Parse("2025-05-15") },
                new SDMTableRow { DatabaseType="SDM_IF_POS", Segment = "IOM LEAD", Market = "US", StoreId = "000018", StoreName = "Store018", DBSizeGB = 9.4563, DBUsedPercent = 5, DBAvailableGB = 6.0, DBAvailablePercent = 90, LastBackupOn = DateTime.Parse("2025-06-15") },
                new SDMTableRow { DatabaseType="SDM_IF_POS", Segment = "IOM LEAD", Market = "CA", StoreId = "000019", StoreName = "Store019", DBSizeGB = 0.0, DBUsedPercent = 22, DBAvailableGB = 7.1, DBAvailablePercent = 76, LastBackupOn = DateTime.Parse("2025-07-15") },

                new SDMTableRow { DatabaseType="SDM_Log_File", Segment = "IOM LEAD", Market = "IN", StoreId = "000020", StoreName = "Store020", DBSizeGB = 180, DBUsedPercent = 100, DBAvailableGB = 0.0, DBAvailablePercent = 0,  LastBackupOn = DateTime.Parse("2025-08-15") },
                new SDMTableRow { DatabaseType="SDM_Log_File", Segment = "IOM LEAD", Market = "UK", StoreId = "000001", StoreName = "Store001", DBSizeGB = 400, DBUsedPercent = 10,  DBAvailableGB = 2,   DBAvailablePercent = 25, LastBackupOn = DateTime.Parse("2025-01-01") },
                new SDMTableRow { DatabaseType="SDM_Log_File", Segment = "IOM LEAD", Market = "US", StoreId = "000002", StoreName = "Store002", DBSizeGB = 200, DBUsedPercent = 20,  DBAvailableGB = 3,   DBAvailablePercent = 35, LastBackupOn = DateTime.Parse("2025-02-01") },
                new SDMTableRow { DatabaseType="SDM_Log_File", Segment = "IOM LEAD", Market = "CA", StoreId = "000003", StoreName = "Store003", DBSizeGB = 300, DBUsedPercent = 30,  DBAvailableGB = 4,   DBAvailablePercent = 45, LastBackupOn = DateTime.Parse("2025-03-01") },
                new SDMTableRow { DatabaseType="SDM_Log_File", Segment = "IOM LEAD", Market = "IN", StoreId = "000004", StoreName = "Store004", DBSizeGB = 635, DBUsedPercent = 40,  DBAvailableGB = 2.5, DBAvailablePercent = 30, LastBackupOn = DateTime.Parse("2025-04-01") },
                new SDMTableRow { DatabaseType="SDM_Log_File", Segment = "IOM LEAD", Market = "UK", StoreId = "000005", StoreName = "Store005", DBSizeGB = 900, DBUsedPercent = 50,  DBAvailableGB = 1.5, DBAvailablePercent = 20, LastBackupOn = DateTime.Parse("2025-05-01") },
                new SDMTableRow { DatabaseType="SDM_Log_File", Segment = "IOM LEAD", Market = "US", StoreId = "000006", StoreName = "Store006", DBSizeGB = 0.0, DBUsedPercent = 60,  DBAvailableGB = 3.3, DBAvailablePercent = 41, LastBackupOn = DateTime.Parse("2025-06-01") },
                new SDMTableRow { DatabaseType="SDM_Log_File", Segment = "IOM LEAD", Market = "CA", StoreId = "000007", StoreName = "Store007", DBSizeGB = 500, DBUsedPercent = 70,  DBAvailableGB = 2.1, DBAvailablePercent = 25, LastBackupOn = DateTime.Parse("2025-07-01") },
                new SDMTableRow { DatabaseType="SDM_Log_File", Segment = "IOM LEAD", Market = "IN", StoreId = "000008", StoreName = "Store008", DBSizeGB = 230, DBUsedPercent = 80,  DBAvailableGB = 1.2, DBAvailablePercent = 15, LastBackupOn = DateTime.Parse("2025-08-01") },
                new SDMTableRow { DatabaseType="SDM_Log_File", Segment = "IOM LEAD", Market = "UK", StoreId = "000009", StoreName = "Store009", DBSizeGB = 1000, DBUsedPercent = 90,  DBAvailableGB = 0.5, DBAvailablePercent = 10, LastBackupOn = DateTime.Parse("2025-09-01") },
                new SDMTableRow { DatabaseType="SDM_Log_File", Segment = "IOM LEAD", Market = "US", StoreId = "000010", StoreName = "Store010", DBSizeGB = 120, DBUsedPercent = 35,  DBAvailableGB = 3.0, DBAvailablePercent = 30, LastBackupOn = DateTime.Parse("2025-10-01") },
                new SDMTableRow { DatabaseType="SDM_Log_File", Segment = "IOM LEAD", Market = "CA", StoreId = "000011", StoreName = "Store011", DBSizeGB = 800, DBUsedPercent = 55,  DBAvailableGB = 1.1, DBAvailablePercent = 15, LastBackupOn = DateTime.Parse("2025-11-01") },
                new SDMTableRow { DatabaseType="SDM_Log_File", Segment = "IOM LEAD", Market = "IN", StoreId = "000012", StoreName = "Store012", DBSizeGB = 387, DBUsedPercent = 25,  DBAvailableGB = 2.5, DBAvailablePercent = 40, LastBackupOn = DateTime.Parse("2025-12-01") },
                new SDMTableRow { DatabaseType="SDM_Log_File", Segment = "IOM LEAD", Market = "UK", StoreId = "000013", StoreName = "Store013", DBSizeGB = 150, DBUsedPercent = 15,  DBAvailableGB = 2.8, DBAvailablePercent = 32, LastBackupOn = DateTime.Parse("2025-01-15") },
                new SDMTableRow { DatabaseType="SDM_Log_File", Segment = "IOM LEAD", Market = "US", StoreId = "000014", StoreName = "Store014", DBSizeGB = 110, DBUsedPercent = 45,  DBAvailableGB = 3.2, DBAvailablePercent = 38, LastBackupOn = DateTime.Parse("2025-02-15") },
                new SDMTableRow { DatabaseType="SDM_Log_File", Segment = "IOM LEAD", Market = "CA", StoreId = "000015", StoreName = "Store015", DBSizeGB = 600, DBUsedPercent = 65,  DBAvailableGB = 1.0, DBAvailablePercent = 12, LastBackupOn = DateTime.Parse("2025-03-15") },
                new SDMTableRow { DatabaseType="SDM_Log_File", Segment = "IOM LEAD", Market = "IN", StoreId = "000016", StoreName = "Store016", DBSizeGB = 400, DBUsedPercent = 85,  DBAvailableGB = 2.9, DBAvailablePercent = 22, LastBackupOn = DateTime.Parse("2025-04-15") },
                new SDMTableRow { DatabaseType="SDM_Log_File", Segment = "IOM LEAD", Market = "UK", StoreId = "000017", StoreName = "Store017", DBSizeGB = 2000, DBUsedPercent = 95,  DBAvailableGB = 0.7, DBAvailablePercent = 8,  LastBackupOn = DateTime.Parse("2025-05-15") },
                new SDMTableRow { DatabaseType="SDM_Log_File", Segment = "IOM LEAD", Market = "US", StoreId = "000018", StoreName = "Store018", DBSizeGB = 300, DBUsedPercent = 5,   DBAvailableGB = 6.0, DBAvailablePercent = 90, LastBackupOn = DateTime.Parse("2025-06-15") },
                new SDMTableRow { DatabaseType="SDM_Log_File", Segment = "IOM LEAD", Market = "CA", StoreId = "000019", StoreName = "Store019", DBSizeGB = 0, DBUsedPercent = 22,  DBAvailableGB = 7.1, DBAvailablePercent = 76, LastBackupOn = DateTime.Parse("2025-07-15") }
            };
        }
    }
}


